--- # Sample play
- hosts: all
  tasks:
    - name: Installing Softwares
      yum: 
        name: elinks
        state: latest


    - name: Installing httpd package
      yum:
        name: httpd
        state: present
      service:
        state: started
        enabled: yes